### ISSUE TITLE
Leaking password

### ISSUE THREAD

**Issue by ChristianSch** [mjaysonnn/DeepSpotCloud#1]
Hey there, 

in the past you had your database password available to the public (see https://github.com/mjaysonnn/DeepSpotCloud/commit/637ed26a9b5dd01dfb5fc7170c5e7b638c3fc023). I was able to log into your database. I don't think it's a good idea to have your password available to the public. I found it via the github search, and so everyone can, even malicious users. I hope no damage has been done yet!

**Comment by mjaysonnn** [comment]
Hello there, thanks for the feedback. now i'm working on to hide commit history if possible, thanks for good advice again :)

**Comment by hyu-leeky** [comment]
changed the password. thank you for the report!
